### PR TITLE
Header bar, refactoring, and disabling window size setter

### LINKED ISSUE #321: Forcing window size leads to being unusable on small screens
**To Reproduce**
1. Open manager on a small screen
2. Explore behavior like this:
picture of convenient_test_manager being messed up

**Expected behavior**
Flutter has out of the box support for resizing content based on screen size
(like with Wrappers, etc). The app adapts to the smaller screen size.

**Additional context**
This happens because of this:
https://github.com/fzyzcjy/flutter_convenient_test/blob/12e774f1ba40410ccec74275b908956780aa74ca/packages/convenient_test_manager/lib/misc/setup.dart#L44

### PR DESCRIPTION
**Pull request by gilice**
Fixes #321.
Also refactors a bit, from functions to widgets, and a new directory for headers.
This did involve disabling the logic to set the window size.
Also adds goldens for this header bar.

on a really small screen:

on a small screen:

on a wide screen:

### CODE REVIEW

**Review by fzyzcjy — COMMENTED** [review]
Good job! two nits and ready to go :)

File: packages/convenient_test_manager/lib/misc/setup.dart [hunk 1]
```diff
@@ -34,8 +30,6 @@ Future<void> setup({
 
   if (initVLC) await DartVLC.initialize();
 
-  if (setWinSize) await _setWindowSize();
```
Comment (fzyzcjy) [inline packages/convenient_test_manager/lib/misc/setup.dart:37]: IMHO it is great to set to the bigger windows size (e.g. the original code - 1350x1000) on larger screens, because the default window size is a bit too small to be used on larger screens. What do you think? One way is to detect screen resolution, and set windows size according to that

Comment (fzyzcjy) [reply packages/convenient_test_manager/lib/misc/setup.dart:37]: > The problem with your (the existing) solution is, that the window then cannot be resized below that size because flutter thinks that that is the minimum size.

Yes, we should allow users to resizes arbitrarily. I meant that, maybe we can provide a bigger *initial* size.

**Comment by fzyzcjy** [comment]
Weirdly the CI does not generate runnable artifact, let me rerun it.

Btw, which platform are you on? If we really want to do that, we have to handle windows+macos+linux.

**Comment by fzyzcjy** [comment]
> already set this size

Hmm a bit confused - which size? IIRC Flutter has a small initial size and I never changed it. By using something like [pub.dev/packages/window_manager](https://pub.dev/packages/window_manager) we can avoid duplicating code

**Comment by fzyzcjy** [comment]
This size (LGTM)

image

**Comment by fzyzcjy** [comment]
Good job!
